language: node_js
node_js: node
env:
  global:
    secure: FU5nL36FCuZjkU3FBNtaO5RqyBOSlAfx4ELU8SresBb/doApw0o/lKXNB3h8wcKej9YnvgPII2OsMKd3VB8xm0xepNDdhfRDeANlPTTWobXKVS962JhV/sJKY2T/187tezb/MjsBnTPY+th+tfuZCaVsqi6Vr1ZrbK8FbDLs6wFP+WpxwXOtcNM3QzbdYndLn0qPUfvbabQGjPi4arDDboftZM0EvCXbYGKVHdRnjKilbuvSuuOcTCag450gRuOukzxlGrtH+PuhLR2rXUhiCkKxcVaDsBHJqFdbcWvJXFTmyD4WSuB7rpHmXGRp4PIHBqQ6L/PO7qOJJ1usg6EOLAbfzjEqluZckFDTDCiZr0MHS1s/WhzgqRE0aM2W4mC/i53B4BteJ+YXPCadf+rklEjxEkApAIEMLb50qr1mYLEK34xH3I6RRM+VMXphB6DZyo6jYBtQ0zSWu44yrftPpzmyvHdf1kbPO/2ZZp5A1hjx4XDg97+Bz5MFcqjrUmEB+dih9lZGbFGxsEz1KEcRo6dEylZPgDJ9bTp8tkkiRdzhFZ0bXZdKGqB6+Gac62tCdhTuwKENcfvishkihZNCTintQZn60rGx30FpRuoxMLVBY0Fbuudrd48QMBReN6RKyIpUgK23aGYiTBMKGKloywC0wdZd9HqjJgyvPSQTOjc=

script: npm run build
before_deploy:
- curl --location --retry 5 --output ossutil 'https://github.com/mycard/ossutil/releases/download/1.0.0.Beta2/ossutil'
- chmod +x ossutil
- ./ossutil config --endpoint oss-cn-hangzhou.aliyuncs.com --access-key-id $ALIYUN_ID
  --access-key-secret $ALIYUN_SECRET
deploy:
  provider: script
  script: ./ossutil cp -rf dist oss://mycard/accounts
  skip_cleanup: true
  on:
    branch: master
